name: Stock Analysis Scheduler

on:
  schedule:
    # Run at 8:00 AM UTC (10:00 AM EET)
    - cron: '0 8 * * 1-5'  # Weekdays only
  workflow_dispatch:  # Manual trigger

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Check environment variables
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "Checking environment variables..."
        echo "TELEGRAM_BOT_TOKEN length: ${#TELEGRAM_BOT_TOKEN}"
        echo "TELEGRAM_CHAT_ID length: ${#TELEGRAM_CHAT_ID}"
        if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
          echo "❌ TELEGRAM_BOT_TOKEN is empty!"
        else
          echo "✅ TELEGRAM_BOT_TOKEN is set"
        fi
        if [ -z "$TELEGRAM_CHAT_ID" ]; then
          echo "❌ TELEGRAM_CHAT_ID is empty!"
        else
          echo "✅ TELEGRAM_CHAT_ID is set"
        fi
    
    - name: Run stock analysis (test version)
      run: |
        python test_github_actions.py